### ISSUE TITLE
what is pagination.total use for

### ISSUE THREAD

**Issue by aaronxie7** [Media24si/vue-pagination#2]
the example have pagination.total, but the source code haven't

```
      pagination: {
        total: 0, // here
        per_page: 12,
        from: 1,
        to: 0,
        current_page: 1
      }
```

**Comment by pogachar** [comment]
It is not needed, but if you ever used Laravel's `->paginate()`, you get response like this:

```
{
   "total": 50,
   "per_page": 15,
   "current_page": 1,
   "last_page": 4,
   "next_page_url": "http://laravel.app?page=2",
   "prev_page_url": null,
   "from": 1,
   "to": 15,
   "data":[...]
}
```

which I mostly just copied. Note that I edited Laravel's response to be like:

```
{
   "pagination": {...}
   "data":[...]
}
```

As long as you can provide `current_page, last_page` (which I forgot to include in example)`, per_page, to`, you don't need Laravel, otherwise just override the pagination when you get the response from your API.
